// roster.js
// Every NCAA programme in the USA that sponsors MEN'S swimming and diving.
//
// This is not the board. The board is the short list Luke is actually working,
// with benchmarks and contacts and a recorded priority. This is the universe
// he can choose from, and its only job is to make sure nothing is missed.
//
// Source: the NCAA's own membership directory, queried on 18 September 2026
// for academic year 2027, ie, the 2026-27 season:
//   https://web3.ncaa.org/directory/api/directory/memberList?type=12&division=I&sportCode=MSW
// The sportCode MSW is men's swimming specifically, so a school that sponsors
// women's swimming and not men's does not appear. That distinction is the
// whole reason to use this source rather than a recruiting site's list, ie,
// the popular published lists carry programmes that were cut years ago and
// miss ones that were added.
//
// What this does NOT tell you: whether a programme has announced it is being
// cut, who coaches it, or how fast its swimmers are. Those come from research
// and live in schools.js against the schools that matter.
//
// Counts at the date recorded: 137 Division I, 77 Division II, 228 Division III.
// 442 programmes in total. Re-run the query to refresh, do not edit by hand.

(function () {

const SOURCE = 'NCAA membership directory, academic year 2027';
const RECORDED = '2026-09-18';

const ROSTER = [
  { id: "american-university", name: "American University", division: 'D1', conference: "Patriot League", state: 'DC', site: "www.aueagles.com" },
  { id: "arizona-state-university", name: "Arizona State University", division: 'D1', conference: "Big 12 Conference", state: 'AZ', site: "sundevils.com" },
  { id: "auburn-university", name: "Auburn University", division: 'D1', conference: "Southeastern Conference", state: 'AL', site: "www.auburntigers.com" },
  { id: "ball-state-university", name: "Ball State University", division: 'D1', conference: "Missouri Valley Conference", state: 'IN', site: "www.ballstatesports.com" },
  { id: "bellarmine-university", name: "Bellarmine University", division: 'D1', conference: "Atlantic Sun Conference", state: 'KY', site: "athletics.bellarmine.edu" },
  { id: "binghamton-university", name: "Binghamton University", division: 'D1', conference: "America East Conference", state: 'NY', site: "www.bubearcats.com" },
  { id: "boston-college", name: "Boston College", division: 'D1', conference: "Atlantic Coast Conference", state: 'MA', site: "www.bceagles.com" },
  { id: "boston-university", name: "Boston University", division: 'D1', conference: "Patriot League", state: 'MA', site: "www.goterriers.com" },
  { id: "brigham-young-university", name: "Brigham Young University", division: 'D1', conference: "Big 12 Conference", state: 'UT', site: "byucougars.com" },
  { id: "brown-university", name: "Brown University", division: 'D1', conference: "The Ivy League", state: 'RI', site: "www.brownbears.com" },
  { id: "bryant-university", name: "Bryant University", division: 'D1', conference: "America East Conference", state: 'RI', site: "www.bryantbulldogs.com" },
  { id: "bucknell-university", name: "Bucknell University", division: 'D1', conference: "Patriot League", state: 'PA', site: "bucknellbison.com" },
  { id: "california-state-university-bakersfield", name: "California State University, Bakersfield", division: 'D1', conference: "Mountain Pacific Sports Federation - Men's Swimming", state: 'CA', site: "www.gorunners.com" },
  { id: "canisius-university", name: "Canisius University", division: 'D1', conference: "Metro Conference", state: 'NY', site: "www.gogriffs.com" },
  { id: "cleveland-state-university", name: "Cleveland State University", division: 'D1', conference: "Horizon League", state: 'OH', site: "www.csuvikings.com" },
  { id: "colgate-university", name: "Colgate University", division: 'D1', conference: "Patriot League", state: 'NY', site: "gocolgateraiders.com" },
  { id: "college-of-the-holy-cross", name: "College of the Holy Cross", division: 'D1', conference: "Patriot League", state: 'MA', site: "goholycross.com" },
  { id: "columbia-university-barnard-college", name: "Columbia University-Barnard College", division: 'D1', conference: "The Ivy League", state: 'NY', site: "www.gocolumbialions.com" },
  { id: "cornell-university", name: "Cornell University", division: 'D1', conference: "The Ivy League", state: 'NY', site: "www.cornellbigred.com" },
  { id: "dartmouth-college", name: "Dartmouth College", division: 'D1', conference: "The Ivy League", state: 'NH', site: "www.dartmouthsports.com" },
  { id: "davidson-college", name: "Davidson College", division: 'D1', conference: "Atlantic 10 Conference", state: 'NC', site: "www.davidsonwildcats.com" },
  { id: "drexel-university", name: "Drexel University", division: 'D1', conference: "Coastal Athletic Association", state: 'PA', site: "www.drexeldragons.com" },
  { id: "duke-university", name: "Duke University", division: 'D1', conference: "Atlantic Coast Conference", state: 'NC', site: "www.goduke.com" },
  { id: "eastern-illinois-university", name: "Eastern Illinois University", division: 'D1', conference: "The Summit League", state: 'IL', site: "www.eiupanthers.com" },
  { id: "fairfield-university", name: "Fairfield University", division: 'D1', conference: "Metro Conference", state: 'CT', site: "fairfieldstags.com" },
  { id: "florida-atlantic-university", name: "Florida Atlantic University", division: 'D1', conference: "Atlantic Sun Conference", state: 'FL', site: "www.fausports.com" },
  { id: "florida-state-university", name: "Florida State University", division: 'D1', conference: "Atlantic Coast Conference", state: 'FL', site: "www.seminoles.com" },
  { id: "fordham-university", name: "Fordham University", division: 'D1', conference: "Atlantic 10 Conference", state: 'NY', site: "www.fordhamsports.com" },
  { id: "gardner-webb-university", name: "Gardner-Webb University", division: 'D1', conference: "Atlantic Sun Conference", state: 'NC', site: "gwusports.com" },
  { id: "george-mason-university", name: "George Mason University", division: 'D1', conference: "Atlantic 10 Conference", state: 'VA', site: "www.gomason.com" },
  { id: "george-washington-university", name: "George Washington University", division: 'D1', conference: "Atlantic 10 Conference", state: 'DC', site: "www.gwsports.com/index.html" },
  { id: "georgetown-university", name: "Georgetown University", division: 'D1', conference: "BIG EAST Conference", state: 'DC', site: "guhoyas.com" },
  { id: "georgia-institute-of-technology", name: "Georgia Institute of Technology", division: 'D1', conference: "Atlantic Coast Conference", state: 'GA', site: "www.ramblinwreck.com" },
  { id: "grand-canyon-university", name: "Grand Canyon University", division: 'D1', conference: "Mountain West Conference", state: 'AZ', site: "www.gculopes.com" },
  { id: "harvard-university", name: "Harvard University", division: 'D1', conference: "The Ivy League", state: 'MA', site: "gocrimson.com" },
  { id: "howard-university", name: "Howard University", division: 'D1', conference: "Northeast Conference", state: 'DC', site: "www.hubison.com" },
  { id: "indiana-university-indianapolis", name: "Indiana University Indianapolis", division: 'D1', conference: "Horizon League", state: 'IN', site: "iuindyjags.com" },
  { id: "indiana-university-bloomington", name: "Indiana University, Bloomington", division: 'D1', conference: "Big Ten Conference", state: 'IN', site: "www.iuhoosiers.com" },
  { id: "iona-university", name: "Iona University", division: 'D1', conference: "Metro Conference", state: 'NY', site: "www.ionagaels.com" },
  { id: "la-salle-university", name: "La Salle University", division: 'D1', conference: "Atlantic 10 Conference", state: 'PA', site: "www.goexplorers.com" },
  { id: "lafayette-college", name: "Lafayette College", division: 'D1', conference: "Patriot League", state: 'PA', site: "www.goleopards.com" },
  { id: "le-moyne-college", name: "Le Moyne College", division: 'D1', conference: "Northeast Conference", state: 'NY', site: "www.lemoynedolphins.com" },
  { id: "lehigh-university", name: "Lehigh University", division: 'D1', conference: "Patriot League", state: 'PA', site: "www.lehighsports.com" },
  { id: "long-island-university", name: "Long Island University", division: 'D1', conference: "Northeast Conference", state: 'NY', site: "www.liuathletics.com" },
  { id: "louisiana-state-university", name: "Louisiana State University", division: 'D1', conference: "Southeastern Conference", state: 'LA', site: "www.lsusports.net" },
  { id: "loyola-university-maryland", name: "Loyola University Maryland", division: 'D1', conference: "Patriot League", state: 'MD', site: "www.loyolagreyhounds.com" },
  { id: "manhattan-university", name: "Manhattan University", division: 'D1', conference: "Metro Conference", state: 'NY', site: "www.gojaspers.com" },
  { id: "marist-university", name: "Marist University", division: 'D1', conference: "Metro Conference", state: 'NY', site: "goredfoxes.com" },
  { id: "miami-university-ohio", name: "Miami University (Ohio)", division: 'D1', conference: "Missouri Valley Conference", state: 'OH', site: "www.miamiredhawks.com" },
  { id: "missouri-state-university", name: "Missouri State University", division: 'D1', conference: "Missouri Valley Conference", state: 'MO', site: "www.missouristatebears.com" },
  { id: "monmouth-university", name: "Monmouth University", division: 'D1', conference: "Coastal Athletic Association", state: 'NJ', site: "www.monmouthhawks.com" },
  { id: "mount-st-mary-s-university", name: "Mount St. Mary's University", division: 'D1', conference: "Metro Conference", state: 'MD', site: "www.mountathletics.com" },
  { id: "new-jersey-institute-of-technology", name: "New Jersey Institute of Technology", division: 'D1', conference: "America East Conference", state: 'NJ', site: "www.njithighlanders.com" },
  { id: "niagara-university", name: "Niagara University", division: 'D1', conference: "Metro Conference", state: 'NY', site: "www.purpleeagles.com" },
  { id: "north-carolina-state-university", name: "North Carolina State University", division: 'D1', conference: "Atlantic Coast Conference", state: 'NC', site: "www.gopack.com" },
  { id: "northern-kentucky-university", name: "Northern Kentucky University", division: 'D1', conference: "Horizon League", state: 'KY', site: "www.nkunorse.com" },
  { id: "northwestern-university", name: "Northwestern University", division: 'D1', conference: "Big Ten Conference", state: 'IL', site: "www.nusports.com" },
  { id: "oakland-university", name: "Oakland University", division: 'D1', conference: "Horizon League", state: 'MI', site: "goldengrizzlies.com" },
  { id: "old-dominion-university", name: "Old Dominion University", division: 'D1', conference: "Atlantic Sun Conference", state: 'VA', site: "www.odusports.com" },
  { id: "pennsylvania-state-university", name: "Pennsylvania State University", division: 'D1', conference: "Big Ten Conference", state: 'PA', site: "gopsusports.com" },
  { id: "princeton-university", name: "Princeton University", division: 'D1', conference: "The Ivy League", state: 'NJ', site: "www.goprincetontigers.com" },
  { id: "providence-college", name: "Providence College", division: 'D1', conference: "BIG EAST Conference", state: 'RI', site: "www.friars.com" },
  { id: "purdue-university", name: "Purdue University", division: 'D1', conference: "Big Ten Conference", state: 'IN', site: "purduesports.com" },
  { id: "queens-university-of-charlotte", name: "Queens University of Charlotte", division: 'D1', conference: "Atlantic Sun Conference", state: 'NC', site: "www.queensathletics.com" },
  { id: "rider-university", name: "Rider University", division: 'D1', conference: "Metro Conference", state: 'NJ', site: "www.gobroncs.com" },
  { id: "saint-louis-university", name: "Saint Louis University", division: 'D1', conference: "Atlantic 10 Conference", state: 'MO', site: "www.slubillikens.com" },
  { id: "saint-mary-s-college-of-california", name: "Saint Mary's College of California", division: 'D1', conference: "Mountain Pacific Sports Federation - Men's Swimming", state: 'CA', site: "www.smcgaels.com" },
  { id: "saint-peter-s-university", name: "Saint Peter's University", division: 'D1', conference: "Metro Conference", state: 'NJ', site: "www.saintpeterspeacocks.com" },
  { id: "seattle-university", name: "Seattle University", division: 'D1', conference: "Mountain Pacific Sports Federation - Men's Swimming", state: 'WA', site: "goseattleu.com" },
  { id: "seton-hall-university", name: "Seton Hall University", division: 'D1', conference: "BIG EAST Conference", state: 'NJ', site: "www.shupirates.com" },
  { id: "south-dakota-state-university", name: "South Dakota State University", division: 'D1', conference: "The Summit League", state: 'SD', site: "www.gojacks.com" },
  { id: "southern-illinois-university-at-carbondale", name: "Southern Illinois University at Carbondale", division: 'D1', conference: "Missouri Valley Conference", state: 'IL', site: "www.siusalukis.com" },
  { id: "southern-methodist-university", name: "Southern Methodist University", division: 'D1', conference: "Atlantic Coast Conference", state: 'TX', site: "www.smumustangs.com" },
  { id: "st-bonaventure-university", name: "St. Bonaventure University", division: 'D1', conference: "Atlantic 10 Conference", state: 'NY', site: "www.gobonnies.com" },
  { id: "stanford-university", name: "Stanford University", division: 'D1', conference: "Atlantic Coast Conference", state: 'CA', site: "gostanford.com" },
  { id: "stonehill-college", name: "Stonehill College", division: 'D1', conference: "Northeast Conference", state: 'MA', site: "www.stonehillskyhawks.com" },
  { id: "texas-a-m-university-college-station", name: "Texas A&M University, College Station", division: 'D1', conference: "Southeastern Conference", state: 'TX', site: "www.12thman.com" },
  { id: "texas-christian-university", name: "Texas Christian University", division: 'D1', conference: "Big 12 Conference", state: 'TX', site: "www.gofrogs.com" },
  { id: "the-ohio-state-university", name: "The Ohio State University", division: 'D1', conference: "Big Ten Conference", state: 'OH', site: "ohiostatebuckeyes.com" },
  { id: "towson-university", name: "Towson University", division: 'D1', conference: "Coastal Athletic Association", state: 'MD', site: "www.towsontigers.com" },
  { id: "u-s-air-force-academy", name: "U.S. Air Force Academy", division: 'D1', conference: "Mountain West Conference", state: 'CO', site: "www.goairforcefalcons.com" },
  { id: "u-s-military-academy", name: "U.S. Military Academy", division: 'D1', conference: "Patriot League", state: 'NY', site: "goarmywestpoint.com/index.aspx" },
  { id: "u-s-naval-academy", name: "U.S. Naval Academy", division: 'D1', conference: "Patriot League", state: 'MD', site: "www.navysports.com" },
  { id: "university-of-alabama", name: "University of Alabama", division: 'D1', conference: "Southeastern Conference", state: 'AL', site: "www.rolltide.com" },
  { id: "university-of-arizona", name: "University of Arizona", division: 'D1', conference: "Big 12 Conference", state: 'AZ', site: "www.arizonawildcats.com" },
  { id: "university-of-california-berkeley", name: "University of California, Berkeley", division: 'D1', conference: "Atlantic Coast Conference", state: 'CA', site: "www.calbears.com" },
  { id: "university-of-california-san-diego", name: "University of California, San Diego", division: 'D1', conference: "Mountain Pacific Sports Federation - Men's Swimming", state: 'CA', site: "www.ucsdtritons.com" },
  { id: "university-of-california-santa-barbara", name: "University of California, Santa Barbara", division: 'D1', conference: "Mountain Pacific Sports Federation - Men's Swimming", state: 'CA', site: "ucsbgauchos.com" },
  { id: "university-of-cincinnati", name: "University of Cincinnati", division: 'D1', conference: "Big 12 Conference", state: 'OH', site: "gobearcats.com" },
  { id: "university-of-delaware", name: "University of Delaware", division: 'D1', conference: "Atlantic Sun Conference", state: 'DE', site: "www.bluehens.com" },
  { id: "university-of-denver", name: "University of Denver", division: 'D1', conference: "Mountain Pacific Sports Federation - Men's Swimming", state: 'CO', site: "denverpioneers.com" },
  { id: "university-of-evansville", name: "University of Evansville", division: 'D1', conference: "Missouri Valley Conference", state: 'IN', site: "www.gopurpleaces.com" },
  { id: "university-of-florida", name: "University of Florida", division: 'D1', conference: "Southeastern Conference", state: 'FL', site: "www.floridagators.com" },
  { id: "university-of-georgia", name: "University of Georgia", division: 'D1', conference: "Southeastern Conference", state: 'GA', site: "www.georgiadogs.com" },
  { id: "university-of-hawaii-manoa", name: "University of Hawaii, Manoa", division: 'D1', conference: "Mountain West Conference", state: 'HI', site: "hawaiiathletics.com" },
  { id: "university-of-illinois-chicago", name: "University of Illinois Chicago", division: 'D1', conference: "Missouri Valley Conference", state: 'IL', site: "www.uicflames.com" },
  { id: "university-of-kentucky", name: "University of Kentucky", division: 'D1', conference: "Southeastern Conference", state: 'KY', site: "www.ukathletics.com" },
  { id: "university-of-louisville", name: "University of Louisville", division: 'D1', conference: "Atlantic Coast Conference", state: 'KY', site: "www.gocards.com" },
  { id: "university-of-maine", name: "University of Maine", division: 'D1', conference: "America East Conference", state: 'ME', site: "goblackbears.com" },
  { id: "university-of-maryland-baltimore-county", name: "University of Maryland, Baltimore County", division: 'D1', conference: "America East Conference", state: 'MD', site: "umbcretrievers.com" },
  { id: "university-of-massachusetts-amherst", name: "University of Massachusetts, Amherst", division: 'D1', conference: "Missouri Valley Conference", state: 'MA', site: "www.umassathletics.com" },
  { id: "university-of-miami-florida", name: "University of Miami (Florida)", division: 'D1', conference: "Atlantic Coast Conference", state: 'FL', site: "miamihurricanes.com" },
  { id: "university-of-michigan", name: "University of Michigan", division: 'D1', conference: "Big Ten Conference", state: 'MI', site: "www.mgoblue.com" },
  { id: "university-of-minnesota-twin-cities", name: "University of Minnesota, Twin Cities", division: 'D1', conference: "Big Ten Conference", state: 'MN', site: "www.gophersports.com" },
  { id: "university-of-missouri-columbia", name: "University of Missouri, Columbia", division: 'D1', conference: "Southeastern Conference", state: 'MO', site: "www.mutigers.com" },
  { id: "university-of-nebraska-at-omaha", name: "University of Nebraska at Omaha", division: 'D1', conference: "The Summit League", state: 'NE', site: "www.omavs.com" },
  { id: "university-of-nevada-las-vegas", name: "University of Nevada, Las Vegas", division: 'D1', conference: "Mountain West Conference", state: 'NV', site: "unlvrebels.com" },
  { id: "university-of-north-carolina-wilmington", name: "University of North Carolina Wilmington", division: 'D1', conference: "Coastal Athletic Association", state: 'NC', site: "www.uncwsports.com" },
  { id: "university-of-north-carolina-chapel-hill", name: "University of North Carolina, Chapel Hill", division: 'D1', conference: "Atlantic Coast Conference", state: 'NC', site: "www.goheels.com" },
  { id: "university-of-notre-dame", name: "University of Notre Dame", division: 'D1', conference: "Atlantic Coast Conference", state: 'IN', site: "www.fightingirish.com" },
  { id: "university-of-pennsylvania", name: "University of Pennsylvania", division: 'D1', conference: "The Ivy League", state: 'PA', site: "www.pennathletics.com" },
  { id: "university-of-pittsburgh", name: "University of Pittsburgh", division: 'D1', conference: "Atlantic Coast Conference", state: 'PA', site: "www.pittsburghpanthers.com" },
  { id: "university-of-south-carolina-columbia", name: "University of South Carolina, Columbia", division: 'D1', conference: "Southeastern Conference", state: 'SC', site: "gamecocksonline.com" },
  { id: "university-of-south-dakota", name: "University of South Dakota", division: 'D1', conference: "The Summit League", state: 'SD', site: "www.goyotes.com" },
  { id: "university-of-southern-california", name: "University of Southern California", division: 'D1', conference: "Big Ten Conference", state: 'CA', site: "usctrojans.com" },
  { id: "university-of-southern-indiana", name: "University of Southern Indiana", division: 'D1', conference: "The Summit League", state: 'IN', site: "www.usiscreamingeagles.com" },
  { id: "university-of-st-thomas-minnesota", name: "University of St. Thomas (Minnesota)", division: 'D1', conference: "The Summit League", state: 'MN', site: "www.tommiesports.com" },
  { id: "university-of-tennessee-knoxville", name: "University of Tennessee, Knoxville", division: 'D1', conference: "Southeastern Conference", state: 'TN', site: "www.utsports.com" },
  { id: "university-of-texas-at-austin", name: "University of Texas at Austin", division: 'D1', conference: "Southeastern Conference", state: 'TX', site: "www.texaslonghorns.com" },
  { id: "university-of-utah", name: "University of Utah", division: 'D1', conference: "Big 12 Conference", state: 'UT', site: "utahutes.com" },
  { id: "university-of-virginia", name: "University of Virginia", division: 'D1', conference: "Atlantic Coast Conference", state: 'VA', site: "www.virginiasports.com" },
  { id: "university-of-wisconsin-green-bay", name: "University of Wisconsin-Green Bay", division: 'D1', conference: "Horizon League", state: 'WI', site: "greenbayphoenix.com" },
  { id: "university-of-wisconsin-madison", name: "University of Wisconsin-Madison", division: 'D1', conference: "Big Ten Conference", state: 'WI', site: "www.uwbadgers.com" },
  { id: "university-of-wisconsin-milwaukee", name: "University of Wisconsin-Milwaukee", division: 'D1', conference: "Horizon League", state: 'WI', site: "www.mkepanthers.com" },
  { id: "university-of-wyoming", name: "University of Wyoming", division: 'D1', conference: "Mountain West Conference", state: 'WY', site: "www.gowyo.com" },
  { id: "university-of-the-incarnate-word", name: "University of the Incarnate Word", division: 'D1', conference: "Mountain Pacific Sports Federation - Men's Swimming", state: 'TX', site: "uiwcardinals.com" },
  { id: "university-of-the-pacific", name: "University of the Pacific", division: 'D1', conference: "Mountain Pacific Sports Federation - Men's Swimming", state: 'CA', site: "www.pacifictigers.com" },
  { id: "valparaiso-university", name: "Valparaiso University", division: 'D1', conference: "Missouri Valley Conference", state: 'IN', site: "www.valpoathletics.com" },
  { id: "villanova-university", name: "Villanova University", division: 'D1', conference: "BIG EAST Conference", state: 'PA', site: "www.villanova.com" },
  { id: "virginia-military-institute", name: "Virginia Military Institute", division: 'D1', conference: "Northeast Conference", state: 'VA', site: "www.vmikeydets.com" },
  { id: "virginia-polytechnic-institute-and-state-univers", name: "Virginia Polytechnic Institute and State University", division: 'D1', conference: "Atlantic Coast Conference", state: 'VA', site: "www.hokiesports.com" },
  { id: "wagner-college", name: "Wagner College", division: 'D1', conference: "Northeast Conference", state: 'NY', site: "www.wagnerathletics.com" },
  { id: "west-virginia-university", name: "West Virginia University", division: 'D1', conference: "Big 12 Conference", state: 'WV', site: "www.wvusports.com" },
  { id: "william-mary", name: "William & Mary", division: 'D1', conference: "Coastal Athletic Association", state: 'VA', site: "www.tribeathletics.com" },
  { id: "xavier-university", name: "Xavier University", division: 'D1', conference: "BIG EAST Conference", state: 'OH', site: "www.goxavier.com" },
  { id: "yale-university", name: "Yale University", division: 'D1', conference: "The Ivy League", state: 'CT', site: "www.yalebulldogs.com" },
  { id: "youngstown-state-university", name: "Youngstown State University", division: 'D1', conference: "Horizon League", state: 'OH', site: "www.ysusports.com" },
  { id: "adams-state-university", name: "Adams State University", division: 'D2', conference: "Rocky Mountain Athletic Conference", state: 'CO', site: "www.asugrizzlies.com" },
  { id: "adelphi-university", name: "Adelphi University", division: 'D2', conference: "Northeast 10 Conference", state: 'NY', site: "www.aupanthers.com" },
  { id: "ashland-university", name: "Ashland University", division: 'D2', conference: "Great Midwest Athletic Conference", state: 'OH', site: "www.goashlandeagles.com" },
  { id: "assumption-university", name: "Assumption University", division: 'D2', conference: "Northeast 10 Conference", state: 'MA', site: "www.assumptiongreyhounds.com" },
  { id: "augustana-university-south-dakota", name: "Augustana University (South Dakota)", division: 'D2', conference: "Great Lakes Intercollegiate Athletic Conference", state: 'SD', site: "www.goaugie.com" },
  { id: "barry-university", name: "Barry University", division: 'D2', conference: "Sunshine State Conference", state: 'FL', site: "www.gobarrybucs.com" },
  { id: "barton-college", name: "Barton College", division: 'D2', conference: "Conference Carolinas", state: 'NC', site: "www.bartonbulldogs.com" },
  { id: "bentley-university", name: "Bentley University", division: 'D2', conference: "Northeast 10 Conference", state: 'MA', site: "www.bentley.edu/athletics" },
  { id: "biola-university", name: "Biola University", division: 'D2', conference: "Independent", state: 'CA', site: "athletics.biola.edu" },
  { id: "bloomsburg-university-of-pennsylvania", name: "Bloomsburg University of Pennsylvania", division: 'D2', conference: "Pennsylvania State Athletic Conference", state: 'PA', site: "www.bloomsburgathletics.com" },
  { id: "carson-newman-university", name: "Carson-Newman University", division: 'D2', conference: "Conference Carolinas", state: 'TN', site: "cneagles.com" },
  { id: "catawba-college", name: "Catawba College", division: 'D2', conference: "Conference Carolinas", state: 'NC', site: "www.catawbaathletics.com" },
  { id: "chowan-university", name: "Chowan University", division: 'D2', conference: "Conference Carolinas", state: 'NC', site: "www.gocuhawks.com" },
  { id: "college-of-staten-island", name: "College of Staten Island", division: 'D2', conference: "Northeast 10 Conference", state: 'NY', site: "www.csidolphins.com" },
  { id: "colorado-mesa-university", name: "Colorado Mesa University", division: 'D2', conference: "Rocky Mountain Athletic Conference", state: 'CO', site: "cmumavericks.com" },
  { id: "colorado-school-of-mines", name: "Colorado School of Mines", division: 'D2', conference: "Rocky Mountain Athletic Conference", state: 'CO', site: "minesathletics.com" },
  { id: "converse-university", name: "Converse University", division: 'D2', conference: "Conference Carolinas", state: 'SC', site: "govalkyries.com" },
  { id: "davenport-university", name: "Davenport University", division: 'D2', conference: "Great Lakes Intercollegiate Athletic Conference", state: 'MI', site: "dupanthers.com" },
  { id: "davis-elkins-college", name: "Davis & Elkins College", division: 'D2', conference: "Great Midwest Athletic Conference", state: 'WV', site: "www.senatornation.com" },
  { id: "delta-state-university", name: "Delta State University", division: 'D2', conference: "Independent", state: 'MS', site: "www.gostatesmen.com" },
  { id: "drury-university", name: "Drury University", division: 'D2', conference: "Great Lakes Valley Conference", state: 'MO', site: "www.drurypanthers.com" },
  { id: "emmanuel-university-georgia", name: "Emmanuel University (Georgia)", division: 'D2', conference: "Conference Carolinas", state: 'GA', site: "www.goeclions.com" },
  { id: "fairmont-state-university", name: "Fairmont State University", division: 'D2', conference: "Great Midwest Athletic Conference", state: 'WV', site: "www.fightingfalcons.com" },
  { id: "felician-university", name: "Felician University", division: 'D2', conference: "Northeast 10 Conference", state: 'NJ', site: "www.felicianuathletics.com" },
  { id: "florida-institute-of-technology", name: "Florida Institute of Technology", division: 'D2', conference: "Sunshine State Conference", state: 'FL', site: "floridatechsports.com" },
  { id: "florida-southern-college", name: "Florida Southern College", division: 'D2', conference: "Sunshine State Conference", state: 'FL', site: "www.fscmocs.com" },
  { id: "fresno-pacific-university", name: "Fresno Pacific University", division: 'D2', conference: "Independent", state: 'CA', site: "fpuathletics.com" },
  { id: "frostburg-state-university", name: "Frostburg State University", division: 'D2', conference: "Great Midwest Athletic Conference", state: 'MD', site: "www.frostburgsports.com" },
  { id: "gannon-university", name: "Gannon University", division: 'D2', conference: "Pennsylvania State Athletic Conference", state: 'PA', site: "www.gannonsports.com" },
  { id: "grand-valley-state-university", name: "Grand Valley State University", division: 'D2', conference: "Great Lakes Intercollegiate Athletic Conference", state: 'MI', site: "gvsulakers.com" },
  { id: "henderson-state-university", name: "Henderson State University", division: 'D2', conference: "Great American Conference", state: 'AR', site: "hsusports.com" },
  { id: "indiana-university-of-pennsylvania", name: "Indiana University of Pennsylvania", division: 'D2', conference: "Pennsylvania State Athletic Conference", state: 'PA', site: "iupathletics.com" },
  { id: "king-university", name: "King University", division: 'D2', conference: "Conference Carolinas", state: 'TN', site: "www.kingtornado.com" },
  { id: "kutztown-university-of-pennsylvania", name: "Kutztown University of Pennsylvania", division: 'D2', conference: "Pennsylvania State Athletic Conference", state: 'PA', site: "www.kubears.com" },
  { id: "lake-superior-state-university", name: "Lake Superior State University", division: 'D2', conference: "Great Lakes Intercollegiate Athletic Conference", state: 'MI', site: "lssulakers.com" },
  { id: "lenoir-rhyne-university", name: "Lenoir-Rhyne University", division: 'D2', conference: "Conference Carolinas", state: 'NC', site: "www.lrbears.com" },
  { id: "lewis-university", name: "Lewis University", division: 'D2', conference: "Great Lakes Valley Conference", state: 'IL', site: "www.lewisflyers.com" },
  { id: "lynn-university", name: "Lynn University", division: 'D2', conference: "Sunshine State Conference", state: 'FL', site: "www.lynnfightingknights.com" },
  { id: "mars-hill-university", name: "Mars Hill University", division: 'D2', conference: "Conference Carolinas", state: 'NC', site: "www.marshilllions.com" },
  { id: "mckendree-university", name: "McKendree University", division: 'D2', conference: "Great Lakes Valley Conference", state: 'IL', site: "www.mckbearcats.com" },
  { id: "missouri-university-of-science-and-technology", name: "Missouri University of Science and Technology", division: 'D2', conference: "Great Lakes Valley Conference", state: 'MO', site: "www.minerathletics.com" },
  { id: "northern-michigan-university", name: "Northern Michigan University", division: 'D2', conference: "Great Lakes Intercollegiate Athletic Conference", state: 'MI', site: "www.nmuwildcats.com" },
  { id: "nova-southeastern-university", name: "Nova Southeastern University", division: 'D2', conference: "Sunshine State Conference", state: 'FL', site: "nsusharks.com" },
  { id: "oklahoma-christian-university", name: "Oklahoma Christian University", division: 'D2', conference: "Rocky Mountain Athletic Conference", state: 'OK', site: "www.oceagles.com" },
  { id: "ouachita-baptist-university", name: "Ouachita Baptist University", division: 'D2', conference: "Independent", state: 'AR', site: "www.obutigers.com" },
  { id: "pace-university", name: "Pace University", division: 'D2', conference: "Northeast 10 Conference", state: 'NY', site: "www.paceuathletics.com" },
  { id: "pennsylvania-western-university-clarion", name: "Pennsylvania Western University, Clarion", division: 'D2', conference: "Pennsylvania State Athletic Conference", state: 'PA', site: "www.clariongoldeneagles.com" },
  { id: "pennsylvania-western-university-edinboro", name: "Pennsylvania Western University, Edinboro", division: 'D2', conference: "Pennsylvania State Athletic Conference", state: 'PA', site: "www.gofightingscots.com" },
  { id: "quincy-university", name: "Quincy University", division: 'D2', conference: "Great Lakes Valley Conference", state: 'IL', site: "quhawks.com" },
  { id: "roberts-wesleyan-university", name: "Roberts Wesleyan University", division: 'D2', conference: "Great Midwest Athletic Conference", state: 'NY', site: "www.robertsredhawks.com" },
  { id: "rockhurst-university", name: "Rockhurst University", division: 'D2', conference: "Great Lakes Valley Conference", state: 'MO', site: "www.rockhursthawks.com" },
  { id: "rollins-college", name: "Rollins College", division: 'D2', conference: "Sunshine State Conference", state: 'FL', site: "rollinssports.com" },
  { id: "saginaw-valley-state-university", name: "Saginaw Valley State University", division: 'D2', conference: "Great Lakes Intercollegiate Athletic Conference", state: 'MI', site: "www.svsucardinals.com" },
  { id: "saint-michael-s-college", name: "Saint Michael's College", division: 'D2', conference: "Northeast 10 Conference", state: 'VT', site: "www.smcathletics.com" },
  { id: "salem-university-west-virginia", name: "Salem University (West Virginia)", division: 'D2', conference: "Great Midwest Athletic Conference", state: 'WV', site: "www.salemtigers.com" },
  { id: "shawnee-state-university", name: "Shawnee State University ", division: 'D2', conference: "Mountain East Conference", state: 'OH', site: "www.ssubears.com" },
  { id: "shippensburg-university-of-pennsylvania", name: "Shippensburg University of Pennsylvania", division: 'D2', conference: "Pennsylvania State Athletic Conference", state: 'PA', site: "www.shipraiders.com" },
  { id: "simon-fraser-university", name: "Simon Fraser University", division: 'D2', conference: "Rocky Mountain Athletic Conference", state: 'BC', site: "athletics.sfu.ca" },
  { id: "southern-connecticut-state-university", name: "Southern Connecticut State University", division: 'D2', conference: "Northeast 10 Conference", state: 'CT', site: "scsuowls.com" },
  { id: "southwest-baptist-university", name: "Southwest Baptist University", division: 'D2', conference: "Great Lakes Valley Conference", state: 'MO', site: "www.sbubearcats.com" },
  { id: "st-cloud-state-university", name: "St. Cloud State University", division: 'D2', conference: "Great Lakes Intercollegiate Athletic Conference", state: 'MN', site: "www.stcloudstate.edu/athletics" },
  { id: "the-university-of-texas-permian-basin", name: "The University of Texas Permian Basin", division: 'D2', conference: "Rocky Mountain Athletic Conference", state: 'TX', site: "www.utpbfalcons.com" },
  { id: "truman-state-university", name: "Truman State University", division: 'D2', conference: "Great Lakes Valley Conference", state: 'MO', site: "www.trumanbulldogs.com" },
  { id: "university-of-bridgeport", name: "University of Bridgeport", division: 'D2', conference: "Northeast 10 Conference", state: 'CT', site: "www.ubknights.com" },
  { id: "university-of-findlay", name: "University of Findlay", division: 'D2', conference: "Great Midwest Athletic Conference", state: 'OH', site: "findlayoilers.com" },
  { id: "university-of-indianapolis", name: "University of Indianapolis", division: 'D2', conference: "Great Lakes Valley Conference", state: 'IN', site: "uindyathletics.com" },
  { id: "university-of-missouri-st-louis", name: "University of Missouri-St. Louis", division: 'D2', conference: "Great Lakes Valley Conference", state: 'MO', site: "umsltritons.com" },
  { id: "university-of-pittsburgh-johnstown", name: "University of Pittsburgh, Johnstown", division: 'D2', conference: "Pennsylvania State Athletic Conference", state: 'PA', site: "pittjohnstownathletics.com" },
  { id: "university-of-puerto-rico-mayaguez", name: "University of Puerto Rico, Mayaguez", division: 'D2', conference: "Independent", state: 'PR', site: "www.uprm.edu/actividadesatleticas" },
  { id: "university-of-tampa", name: "University of Tampa", division: 'D2', conference: "Sunshine State Conference", state: 'FL', site: "tampaspartans.com/landing/index" },
  { id: "walsh-university", name: "Walsh University", division: 'D2', conference: "Great Midwest Athletic Conference", state: 'OH', site: "athletics.walsh.edu/landing/index" },
  { id: "wayne-state-university-michigan", name: "Wayne State University (Michigan)", division: 'D2', conference: "Great Lakes Intercollegiate Athletic Conference", state: 'MI', site: "www.wsuathletics.com" },
  { id: "west-chester-university-of-pennsylvania", name: "West Chester University of Pennsylvania", division: 'D2', conference: "Pennsylvania State Athletic Conference", state: 'PA', site: "www.wcupagoldenrams.com" },
  { id: "west-virginia-wesleyan-college", name: "West Virginia Wesleyan College", division: 'D2', conference: "Great Midwest Athletic Conference", state: 'WV', site: "wesleyanbobcats.com" },
  { id: "wheeling-university", name: "Wheeling University", division: 'D2', conference: "Great Midwest Athletic Conference", state: 'WV', site: "wucardinals.com" },
  { id: "william-jewell-college", name: "William Jewell College", division: 'D2', conference: "Great Lakes Valley Conference", state: 'MO', site: "www.jewellcardinals.com" },
  { id: "wingate-university", name: "Wingate University", division: 'D2', conference: "Conference Carolinas", state: 'NC', site: "wingatebulldogs.com" },
  { id: "albion-college", name: "Albion College", division: 'D3', conference: "Michigan Intercollegiate Athletic Association", state: 'MI', site: "www.gobrits.com" },
  { id: "alfred-university", name: "Alfred University", division: 'D3', conference: "Empire 8", state: 'NY', site: "www.gosaxons.com" },
  { id: "allegheny-college", name: "Allegheny College", division: 'D3', conference: "Presidents' Athletic Conference", state: 'PA', site: "www.alleghenygators.com" },
  { id: "alma-college", name: "Alma College", division: 'D3', conference: "Michigan Intercollegiate Athletic Association", state: 'MI', site: "www.almascots.com" },
  { id: "amherst-college", name: "Amherst College", division: 'D3', conference: "New England Small College Athletic Conference", state: 'MA', site: "athletics.amherst.edu/landing/index" },
  { id: "anderson-university-indiana", name: "Anderson University (Indiana)", division: 'D3', conference: "Heartland Collegiate Athletic Conference", state: 'IN', site: "athletics.anderson.edu" },
  { id: "arcadia-university", name: "Arcadia University", division: 'D3', conference: "Middle Atlantic Conferences", state: 'PA', site: "www.arcadiaknights.com" },
  { id: "asbury-university", name: "Asbury University", division: 'D3', conference: "Southern Collegiate Athletic Conference", state: 'KY', site: "www.asburyeagles.com" },
  { id: "augustana-college-illinois", name: "Augustana College (Illinois)", division: 'D3', conference: "College Conference of Illinois & Wisconsin", state: 'IL', site: "www.athletics.augustana.edu" },
  { id: "austin-college", name: "Austin College", division: 'D3', conference: "Southern Collegiate Athletic Conference", state: 'TX', site: "www.acroos.com" },
  { id: "babson-college", name: "Babson College", division: 'D3', conference: "New England Women's and Men's Athletic Conference", state: 'MA', site: "www.babsonathletics.com" },
  { id: "baldwin-wallace-university", name: "Baldwin Wallace University", division: 'D3', conference: "Ohio Athletic Conference", state: 'OH', site: "www.bwyellowjackets.com/landing/index" },
  { id: "bard-college", name: "Bard College", division: 'D3', conference: "Liberty League", state: 'NY', site: "www.bardathletics.com" },
  { id: "baruch-college", name: "Baruch College", division: 'D3', conference: "City University of New York Athletic Conference", state: 'NY', site: "www.baruchathletics.com" },
  { id: "bates-college", name: "Bates College", division: 'D3', conference: "New England Small College Athletic Conference", state: 'ME', site: "www.gobatesbobcats.com" },
  { id: "batten-university", name: "Batten University", division: 'D3', conference: "Old Dominion Athletic Conf.", state: 'VA', site: "vwuathletics.com" },
  { id: "beloit-college", name: "Beloit College", division: 'D3', conference: "Midwest Conference", state: 'WI', site: "www.beloit.edu/bucs" },
  { id: "berry-college", name: "Berry College", division: 'D3', conference: "Southern Athletic Association", state: 'GA', site: "www.berryvikings.com" },
  { id: "bethany-college-west-virginia", name: "Bethany College (West Virginia)", division: 'D3', conference: "Presidents' Athletic Conference", state: 'WV', site: "bethanybison.com" },
  { id: "bowdoin-college", name: "Bowdoin College", division: 'D3', conference: "New England Small College Athletic Conference", state: 'ME', site: "www.bowdoin.edu/athletics" },
  { id: "brandeis-university", name: "Brandeis University", division: 'D3', conference: "University Athletic Association", state: 'MA', site: "www.brandeisjudges.com" },
  { id: "bridgewater-college-virginia", name: "Bridgewater College (Virginia)", division: 'D3', conference: "Old Dominion Athletic Conf.", state: 'VA', site: "www.bridgewatereagles.com" },
  { id: "bridgewater-state-university", name: "Bridgewater State University", division: 'D3', conference: "Little East Conference", state: 'MA', site: "www.bsubears.com" },
  { id: "brooklyn-college", name: "Brooklyn College", division: 'D3', conference: "City University of New York Athletic Conference", state: 'NY', site: "brooklyncollegeathletics.com" },
  { id: "california-institute-of-technology", name: "California Institute of Technology", division: 'D3', conference: "Southern California Intercollegiate Athletic Conf.", state: 'CA', site: "www.gocaltech.com" },
  { id: "california-lutheran-university", name: "California Lutheran University", division: 'D3', conference: "Southern California Intercollegiate Athletic Conf.", state: 'CA', site: "www.clusports.com" },
  { id: "calvin-university", name: "Calvin University", division: 'D3', conference: "Michigan Intercollegiate Athletic Association", state: 'MI', site: "calvinknights.com" },
  { id: "carleton-college", name: "Carleton College", division: 'D3', conference: "Minnesota Intercollegiate Athletic Conference", state: 'MN', site: "apps.carleton.edu/athletics" },
  { id: "carnegie-mellon-university", name: "Carnegie Mellon University", division: 'D3', conference: "University Athletic Association", state: 'PA', site: "athletics.cmu.edu" },
  { id: "carroll-university-wisconsin", name: "Carroll University (Wisconsin)", division: 'D3', conference: "College Conference of Illinois & Wisconsin", state: 'WI', site: "www.gopios.com" },
  { id: "carthage-college", name: "Carthage College", division: 'D3', conference: "College Conference of Illinois & Wisconsin", state: 'WI', site: "athletics.carthage.edu" },
  { id: "case-western-reserve-university", name: "Case Western Reserve University", division: 'D3', conference: "University Athletic Association", state: 'OH', site: "athletics.case.edu" },
  { id: "catholic-university", name: "Catholic University", division: 'D3', conference: "Landmark Conference", state: 'DC', site: "www.catholicathletics.com" },
  { id: "centenary-college-louisiana", name: "Centenary College (Louisiana)", division: 'D3', conference: "Southern Collegiate Athletic Conference", state: 'LA', site: "www.gocentenary.com" },
  { id: "centre-college", name: "Centre College", division: 'D3', conference: "Southern Athletic Association", state: 'KY', site: "www.centrecolonels.com" },
  { id: "chapman-university", name: "Chapman University", division: 'D3', conference: "Southern California Intercollegiate Athletic Conf.", state: 'CA', site: "www.chapmanathletics.com" },
  { id: "chatham-university", name: "Chatham University", division: 'D3', conference: "Presidents' Athletic Conference", state: 'PA', site: "www.gochathamcougars.com" },
  { id: "claremont-mckenna-harvey-mudd-scripps-colleges", name: "Claremont McKenna-Harvey Mudd-Scripps Colleges", division: 'D3', conference: "Southern California Intercollegiate Athletic Conf.", state: 'CA', site: "www.cmsathletics.org" },
  { id: "clark-university-massachusetts", name: "Clark University (Massachusetts)", division: 'D3', conference: "New England Women's and Men's Athletic Conference", state: 'MA', site: "clarkathletics.com" },
  { id: "clarkson-university", name: "Clarkson University", division: 'D3', conference: "Liberty League", state: 'NY', site: "www.clarksonathletics.com" },
  { id: "coe-college", name: "Coe College", division: 'D3', conference: "American Rivers Conference", state: 'IA', site: "www.kohawkathletics.com" },
  { id: "colby-college", name: "Colby College", division: 'D3', conference: "New England Small College Athletic Conference", state: 'ME', site: "www.colby.edu/athletics" },
  { id: "colorado-college", name: "Colorado College", division: 'D3', conference: "Southern Collegiate Athletic Conference", state: 'CO', site: "www.cctigers.com" },
  { id: "connecticut-college", name: "Connecticut College", division: 'D3', conference: "New England Small College Athletic Conference", state: 'CT', site: "camelathletics.com" },
  { id: "depauw-university", name: "DePauw University", division: 'D3', conference: "North Coast Athletic Conference", state: 'IN', site: "depauwtigers.com/landing/index" },
  { id: "denison-university", name: "Denison University", division: 'D3', conference: "North Coast Athletic Conference", state: 'OH', site: "www.denisonbigred.com" },
  { id: "dickinson-college", name: "Dickinson College", division: 'D3', conference: "Centennial Conference", state: 'PA', site: "www.dickinsonathletics.com" },
  { id: "drew-university", name: "Drew University", division: 'D3', conference: "Landmark Conference", state: 'NJ', site: "www.drewrangers.com" },
  { id: "eastern-connecticut-state-university", name: "Eastern Connecticut State University", division: 'D3', conference: "Little East Conference", state: 'CT', site: "gowarriorathletics.com" },
  { id: "elizabethtown-college", name: "Elizabethtown College", division: 'D3', conference: "Landmark Conference", state: 'PA', site: "www.etownbluejays.com" },
  { id: "elms-college", name: "Elms College", division: 'D3', conference: "Great Northeast Athletic Conference", state: 'MA', site: "ecblazers.com" },
  { id: "emory-university", name: "Emory University", division: 'D3', conference: "University Athletic Association", state: 'GA', site: "www.emoryathletics.com" },
  { id: "fairleigh-dickinson-university-florham", name: "Fairleigh Dickinson University, Florham", division: 'D3', conference: "Middle Atlantic Conferences", state: 'NJ', site: "www.fdudevils.com" },
  { id: "franklin-marshall-college", name: "Franklin & Marshall College", division: 'D3', conference: "Centennial Conference", state: 'PA', site: "www.godiplomats.com" },
  { id: "franklin-college", name: "Franklin College", division: 'D3', conference: "Heartland Collegiate Athletic Conference", state: 'IN', site: "franklingrizzlies.com/landing/index" },
  { id: "gallaudet-university", name: "Gallaudet University", division: 'D3', conference: "Atlantic East Conference", state: 'DC', site: "www.gallaudetbison.com" },
  { id: "george-fox-university", name: "George Fox University", division: 'D3', conference: "Northwest Conference", state: 'OR', site: "www.gfubruins.com" },
  { id: "gettysburg-college", name: "Gettysburg College", division: 'D3', conference: "Centennial Conference", state: 'PA', site: "www.gettysburgsports.com" },
  { id: "gordon-college", name: "Gordon College", division: 'D3', conference: "Little East Conference", state: 'MA', site: "athletics.gordon.edu/index.aspx" },
  { id: "goucher-college", name: "Goucher College", division: 'D3', conference: "Landmark Conference", state: 'MD', site: "athletics.goucher.edu/landing/index" },
  { id: "greensboro-college", name: "Greensboro College", division: 'D3', conference: "Old Dominion Athletic Conf.", state: 'NC', site: "www.greensborocollegesports.com" },
  { id: "grinnell-college", name: "Grinnell College", division: 'D3', conference: "Midwest Conference", state: 'IA', site: "pioneers.grinnell.edu" },
  { id: "grove-city-college", name: "Grove City College", division: 'D3', conference: "Presidents' Athletic Conference", state: 'PA', site: "athletics.gcc.edu" },
  { id: "gustavus-adolphus-college", name: "Gustavus Adolphus College", division: 'D3', conference: "Minnesota Intercollegiate Athletic Conference", state: 'MN', site: "www.gustavus.edu/athletics" },
  { id: "hamilton-college", name: "Hamilton College", division: 'D3', conference: "New England Small College Athletic Conference", state: 'NY', site: "www.hamilton.edu/athletics" },
  { id: "hamline-university", name: "Hamline University", division: 'D3', conference: "Minnesota Intercollegiate Athletic Conference", state: 'MN', site: "www.hamlineathletics.com" },
  { id: "hampden-sydney-college", name: "Hampden-Sydney College", division: 'D3', conference: "Old Dominion Athletic Conf.", state: 'VA', site: "www.hscathletics.com" },
  { id: "hartwick-college", name: "Hartwick College", division: 'D3', conference: "Empire 8", state: 'NY', site: "www.hartwickhawks.com" },
  { id: "heidelberg-university", name: "Heidelberg University", division: 'D3', conference: "Ohio Athletic Conference", state: 'OH', site: "bergathletics.com" },
  { id: "hendrix-college", name: "Hendrix College", division: 'D3', conference: "Southern Collegiate Athletic Conference", state: 'AR', site: "www.hendrixwarriors.com" },
  { id: "hiram-college", name: "Hiram College", division: 'D3', conference: "Presidents' Athletic Conference", state: 'OH', site: "www.hiramterriers.com" },
  { id: "hobart-and-william-smith-colleges", name: "Hobart and William Smith Colleges", division: 'D3', conference: "Liberty League", state: 'NY', site: "www.hwsathletics.com" },
  { id: "hood-college", name: "Hood College", division: 'D3', conference: "Middle Atlantic Conferences", state: 'MD', site: "www.hoodathletics.com" },
  { id: "hope-college", name: "Hope College", division: 'D3', conference: "Michigan Intercollegiate Athletic Association", state: 'MI', site: "athletics.hope.edu" },
  { id: "husson-university", name: "Husson University", division: 'D3', conference: "Little East Conference", state: 'ME', site: "www.hussoneagles.com" },
  { id: "illinois-college", name: "Illinois College", division: 'D3', conference: "Midwest Conference", state: 'IL', site: "www.illinoiscollegeathletics.com" },
  { id: "illinois-institute-of-technology", name: "Illinois Institute of Technology", division: 'D3', conference: "Independent", state: 'IL', site: "www.illinoistechathletics.com" },
  { id: "illinois-wesleyan-university", name: "Illinois Wesleyan University", division: 'D3', conference: "College Conference of Illinois & Wisconsin", state: 'IL', site: "www.iwusports.com" },
  { id: "immaculata-university", name: "Immaculata University", division: 'D3', conference: "Atlantic East Conference", state: 'PA', site: "www.gomightymacs.com" },
  { id: "ithaca-college", name: "Ithaca College", division: 'D3', conference: "Liberty League", state: 'NY', site: "athletics.ithaca.edu" },
  { id: "john-carroll-university", name: "John Carroll University", division: 'D3', conference: "North Coast Athletic Conference", state: 'OH', site: "www.jcusports.com" },
  { id: "johns-hopkins-university", name: "Johns Hopkins University", division: 'D3', conference: "Centennial Conference", state: 'MD', site: "www.hopkinssports.com" },
  { id: "juniata-college", name: "Juniata College", division: 'D3', conference: "Landmark Conference", state: 'PA', site: "www.juniatasports.net" },
  { id: "kalamazoo-college", name: "Kalamazoo College", division: 'D3', conference: "Michigan Intercollegiate Athletic Association", state: 'MI', site: "hornets.kzoo.edu/landing/index" },
  { id: "keene-state-college", name: "Keene State College", division: 'D3', conference: "Little East Conference", state: 'NH', site: "www.keeneowls.com" },
  { id: "kenyon-college", name: "Kenyon College", division: 'D3', conference: "North Coast Athletic Conference", state: 'OH', site: "athletics.kenyon.edu" },
  { id: "king-s-college-pennsylvania", name: "King's College (Pennsylvania)", division: 'D3', conference: "Middle Atlantic Conferences", state: 'PA', site: "www.kings.edu/athletics" },
  { id: "lake-forest-college", name: "Lake Forest College", division: 'D3', conference: "Midwest Conference", state: 'IL', site: "www.goforesters.com" },
  { id: "lawrence-university", name: "Lawrence University", division: 'D3', conference: "Midwest Conference", state: 'WI', site: "vikings.lawrence.edu/index.aspx" },
  { id: "lebanon-valley-college", name: "Lebanon Valley College", division: 'D3', conference: "Middle Atlantic Conferences", state: 'PA', site: "www.godutchmen.com" },
  { id: "lehman-college", name: "Lehman College", division: 'D3', conference: "City University of New York Athletic Conference", state: 'NY', site: "www.lehmanathletics.com" },
  { id: "lewis-clark-college", name: "Lewis & Clark College", division: 'D3', conference: "Northwest Conference", state: 'OR', site: "www.golcathletics.com" },
  { id: "linfield-university", name: "Linfield University", division: 'D3', conference: "Northwest Conference", state: 'OR', site: "golinfieldwildcats.com" },
  { id: "loras-college", name: "Loras College", division: 'D3', conference: "American Rivers Conference", state: 'IA', site: "www.duhawks.com" },
  { id: "luther-college", name: "Luther College", division: 'D3', conference: "Midwest Conference", state: 'IA', site: "sports.luther.edu" },
  { id: "lycoming-college", name: "Lycoming College", division: 'D3', conference: "Landmark Conference", state: 'PA', site: "lycomingathletics.com" },
  { id: "macalester-college", name: "Macalester College", division: 'D3', conference: "Minnesota Intercollegiate Athletic Conference", state: 'MN', site: "www.macalester.edu/athletics" },
  { id: "maine-maritime-academy", name: "Maine Maritime Academy", division: 'D3', conference: "Little East Conference", state: 'ME', site: "www.marinersports.org" },
  { id: "manchester-university", name: "Manchester University", division: 'D3', conference: "Heartland Collegiate Athletic Conference", state: 'IN', site: "www.muspartans.com" },
  { id: "marymount-university-virginia", name: "Marymount University (Virginia)", division: 'D3', conference: "Atlantic East Conference", state: 'VA', site: "www.marymountsaints.com" },
  { id: "marywood-university", name: "Marywood University", division: 'D3', conference: "Middle Atlantic Conferences", state: 'PA', site: "www.marywoodpacers.com" },
  { id: "massachusetts-institute-of-technology", name: "Massachusetts Institute of Technology", division: 'D3', conference: "New England Women's and Men's Athletic Conference", state: 'MA', site: "www.mitathletics.com" },
  { id: "mcdaniel-college", name: "McDaniel College", division: 'D3', conference: "Centennial Conference", state: 'MD', site: "www.mcdaniel.edu/athletics" },
  { id: "mcmurry-university", name: "McMurry University", division: 'D3', conference: "Southern Collegiate Athletic Conference", state: 'TX', site: "www.mcmurrysports.com" },
  { id: "messiah-university", name: "Messiah University", division: 'D3', conference: "Middle Atlantic Conferences", state: 'PA', site: "www.gomessiah.com" },
  { id: "middlebury-college", name: "Middlebury College", division: 'D3', conference: "New England Small College Athletic Conference", state: 'VT', site: "www.middlebury.edu/athletics" },
  { id: "millikin-university", name: "Millikin University", division: 'D3', conference: "College Conference of Illinois & Wisconsin", state: 'IL', site: "athletics.millikin.edu" },
  { id: "millsaps-college", name: "Millsaps College", division: 'D3', conference: "Southern Athletic Association", state: 'MS', site: "www.gomajors.com" },
  { id: "milwaukee-school-of-engineering", name: "Milwaukee School of Engineering", division: 'D3', conference: "Midwest Conference", state: 'WI', site: "go-raiders.com" },
  { id: "misericordia-university", name: "Misericordia University", division: 'D3', conference: "Middle Atlantic Conferences", state: 'PA', site: "www.misericordia.edu/athletics" },
  { id: "monmouth-college-illinois", name: "Monmouth College (Illinois)", division: 'D3', conference: "Midwest Conference", state: 'IL', site: "monmouthscots.com" },
  { id: "montclair-state-university", name: "Montclair State University", division: 'D3', conference: "New Jersey Athletic Conference", state: 'NJ', site: "www.montclairathletics.com" },
  { id: "moravian-university", name: "Moravian University", division: 'D3', conference: "Landmark Conference", state: 'PA', site: "moraviansports.com/landing/index" },
  { id: "mount-saint-mary-college-new-york", name: "Mount Saint Mary College (New York)", division: 'D3', conference: "Skyline Conference", state: 'NY', site: "www.msmcknights.com" },
  { id: "nazareth-university", name: "Nazareth University", division: 'D3', conference: "Empire 8", state: 'NY', site: "www.nazathletics.com" },
  { id: "nebraska-wesleyan-university", name: "Nebraska Wesleyan University", division: 'D3', conference: "American Rivers Conference", state: 'NE', site: "www.nwusports.com" },
  { id: "new-york-university", name: "New York University", division: 'D3', conference: "University Athletic Association", state: 'NY', site: "www.gonyuathletics.com" },
  { id: "north-central-college", name: "North Central College", division: 'D3', conference: "College Conference of Illinois & Wisconsin", state: 'IL', site: "northcentralcardinals.com" },
  { id: "norwich-university", name: "Norwich University", division: 'D3', conference: "Great Northeast Athletic Conference", state: 'VT', site: "www.norwichathletics.com" },
  { id: "oberlin-college", name: "Oberlin College", division: 'D3', conference: "North Coast Athletic Conference", state: 'OH', site: "www.goyeo.com" },
  { id: "occidental-college", name: "Occidental College", division: 'D3', conference: "Southern California Intercollegiate Athletic Conf.", state: 'CA', site: "www.oxyathletics.com" },
  { id: "ohio-northern-university", name: "Ohio Northern University", division: 'D3', conference: "Ohio Athletic Conference", state: 'OH', site: "onusports.com/landing/index" },
  { id: "ohio-wesleyan-university", name: "Ohio Wesleyan University", division: 'D3', conference: "North Coast Athletic Conference", state: 'OH', site: "battlingbishops.com" },
  { id: "pacific-lutheran-university", name: "Pacific Lutheran University", division: 'D3', conference: "Northwest Conference", state: 'WA', site: "www.golutes.com" },
  { id: "pacific-university-oregon", name: "Pacific University (Oregon)", division: 'D3', conference: "Northwest Conference", state: 'OR', site: "www.goboxers.com" },
  { id: "penn-state-university-altoona", name: "Penn State University, Altoona", division: 'D3', conference: "State University of New York Athletic Conference", state: 'PA', site: "www.psaltoonalions.com" },
  { id: "pennsylvania-state-univ-erie-the-behrend-college", name: "Pennsylvania State Univ. Erie, the Behrend College", division: 'D3', conference: "State University of New York Athletic Conference", state: 'PA', site: "psblions.com" },
  { id: "piedmont-university", name: "Piedmont University", division: 'D3', conference: "Independent", state: 'GA', site: "www.piedmontlions.com" },
  { id: "plymouth-state-university", name: "Plymouth State University", division: 'D3', conference: "Little East Conference", state: 'NH', site: "athletics.plymouth.edu" },
  { id: "pomona-pitzer-colleges", name: "Pomona-Pitzer Colleges", division: 'D3', conference: "Southern California Intercollegiate Athletic Conf.", state: 'CA', site: "www.sagehens.com" },
  { id: "ramapo-college", name: "Ramapo College", division: 'D3', conference: "New Jersey Athletic Conference", state: 'NJ', site: "www.ramapoathletics.com" },
  { id: "randolph-college", name: "Randolph College", division: 'D3', conference: "Old Dominion Athletic Conf.", state: 'VA', site: "www.randolphwildcats.com" },
  { id: "randolph-macon-college", name: "Randolph-Macon College", division: 'D3', conference: "Old Dominion Athletic Conf.", state: 'VA', site: "www.rmcathletics.com" },
  { id: "regis-college-massachusetts", name: "Regis College (Massachusetts)", division: 'D3', conference: "Great Northeast Athletic Conference", state: 'MA', site: "www.goregispride.com" },
  { id: "rensselaer-polytechnic-institute", name: "Rensselaer Polytechnic Institute", division: 'D3', conference: "Liberty League", state: 'NY', site: "www.rpiathletics.com" },
  { id: "rhodes-college", name: "Rhodes College", division: 'D3', conference: "Southern Athletic Association", state: 'TN', site: "www.rhodeslynx.com" },
  { id: "ripon-college", name: "Ripon College", division: 'D3', conference: "Midwest Conference", state: 'WI', site: "riponredhawks.com" },
  { id: "roanoke-college", name: "Roanoke College", division: 'D3', conference: "Old Dominion Athletic Conf.", state: 'VA', site: "maroons.roanoke.edu" },
  { id: "rochester-institute-of-technology", name: "Rochester Institute of Technology", division: 'D3', conference: "Liberty League", state: 'NY', site: "www.ritathletics.com" },
  { id: "roger-williams-university", name: "Roger Williams University", division: 'D3', conference: "New Jersey Athletic Conference", state: 'RI', site: "www.rwuhawks.com" },
  { id: "rose-hulman-institute-of-technology", name: "Rose-Hulman Institute of Technology", division: 'D3', conference: "Heartland Collegiate Athletic Conference", state: 'IN', site: "www.rose-hulman.edu/athletics" },
  { id: "rowan-university", name: "Rowan University", division: 'D3', conference: "New Jersey Athletic Conference", state: 'NJ', site: "www.rowanathletics.com" },
  { id: "saint-francis-university", name: "Saint Francis University ", division: 'D3', conference: "Presidents' Athletic Conference", state: 'PA', site: "www.sfuathletics.com" },
  { id: "saint-john-s-university-minnesota", name: "Saint John's University (Minnesota)", division: 'D3', conference: "Minnesota Intercollegiate Athletic Conference", state: 'MN', site: "www.gojohnnies.com" },
  { id: "saint-joseph-s-college-maine", name: "Saint Joseph's College (Maine)", division: 'D3', conference: "Great Northeast Athletic Conference", state: 'ME', site: "www.gomonks.com" },
  { id: "saint-vincent-college", name: "Saint Vincent College", division: 'D3', conference: "Presidents' Athletic Conference", state: 'PA', site: "www.athletics.stvincent.edu" },
  { id: "salisbury-university", name: "Salisbury University", division: 'D3', conference: "New Jersey Athletic Conference", state: 'MD', site: "www.suseagulls.com" },
  { id: "sarah-lawrence-college", name: "Sarah Lawrence College", division: 'D3', conference: "Skyline Conference", state: 'NY', site: "www.gogryphons.com" },
  { id: "skidmore-college", name: "Skidmore College", division: 'D3', conference: "Liberty League", state: 'NY', site: "skidmoreathletics.com" },
  { id: "southern-virginia-university", name: "Southern Virginia University", division: 'D3', conference: "USA South Athletic Conference", state: 'VA', site: "knightathletics.com" },
  { id: "southwestern-university-texas", name: "Southwestern University (Texas)", division: 'D3', conference: "Southern Athletic Association", state: 'TX', site: "www.southwesternpirates.com" },
  { id: "springfield-college", name: "Springfield College", division: 'D3', conference: "New England Women's and Men's Athletic Conference", state: 'MA', site: "springfield.edu/directory/athletics" },
  { id: "st-joseph-s-university-new-york-l-i", name: "St. Joseph's University, New York L.I.", division: 'D3', conference: "Skyline Conference", state: 'NY', site: "www.sjliathletics.com" },
  { id: "st-lawrence-university", name: "St. Lawrence University", division: 'D3', conference: "Liberty League", state: 'NY', site: "www.saintsathletics.com" },
  { id: "st-mary-s-college-of-maryland", name: "St. Mary's College of Maryland", division: 'D3', conference: "Atlantic East Conference", state: 'MD', site: "www.smcmathletics.com" },
  { id: "st-norbert-college", name: "St. Norbert College", division: 'D3', conference: "Midwest Conference", state: 'WI', site: "athletics.snc.edu" },
  { id: "st-olaf-college", name: "St. Olaf College", division: 'D3', conference: "Minnesota Intercollegiate Athletic Conference", state: 'MN', site: "athletics.stolaf.edu" },
  { id: "state-university-of-new-york-maritime-college", name: "State University of New York Maritime College", division: 'D3', conference: "Skyline Conference", state: 'NY', site: "www.maritimeathletics.com" },
  { id: "state-university-of-new-york-at-brockport", name: "State University of New York at Brockport", division: 'D3', conference: "Empire 8", state: 'NY', site: "gobrockport.com" },
  { id: "state-university-of-new-york-at-cortland", name: "State University of New York at Cortland", division: 'D3', conference: "State University of New York Athletic Conference", state: 'NY', site: "www.cortland.edu/athletics" },
  { id: "state-university-of-new-york-at-delhi", name: "State University of New York at Delhi", division: 'D3', conference: "State University of New York Athletic Conference", state: 'NY', site: "delhibroncos.com/landing/index" },
  { id: "state-university-of-new-york-at-geneseo", name: "State University of New York at Geneseo", division: 'D3', conference: "Empire 8", state: 'NY', site: "www.geneseoknights.com" },
  { id: "state-university-of-new-york-at-new-paltz", name: "State University of New York at New Paltz", division: 'D3', conference: "New Jersey Athletic Conference", state: 'NY', site: "www.nphawks.com" },
  { id: "state-university-of-new-york-at-oneonta", name: "State University of New York at Oneonta", division: 'D3', conference: "State University of New York Athletic Conference", state: 'NY', site: "www.oneontaathletics.com" },
  { id: "state-university-of-new-york-at-oswego", name: "State University of New York at Oswego", division: 'D3', conference: "State University of New York Athletic Conference", state: 'NY', site: "oswegolakers.com" },
  { id: "state-university-of-new-york-at-potsdam", name: "State University of New York at Potsdam", division: 'D3', conference: "State University of New York Athletic Conference", state: 'NY', site: "www.potsdambears.com" },
  { id: "stevens-institute-of-technology", name: "Stevens Institute of Technology", division: 'D3', conference: "Middle Atlantic Conferences", state: 'NJ', site: "www.stevensducks.com" },
  { id: "stevenson-university", name: "Stevenson University", division: 'D3', conference: "Middle Atlantic Conferences", state: 'MD', site: "www.gomustangsports.com" },
  { id: "susquehanna-university", name: "Susquehanna University", division: 'D3', conference: "Landmark Conference", state: 'PA', site: "www.gosusqu.com" },
  { id: "swarthmore-college", name: "Swarthmore College", division: 'D3', conference: "Centennial Conference", state: 'PA', site: "swarthmoreathletics.com" },
  { id: "the-college-of-new-jersey", name: "The College of New Jersey", division: 'D3', conference: "New Jersey Athletic Conference", state: 'NJ', site: "www.tcnjathletics.com" },
  { id: "the-college-of-wooster", name: "The College of Wooster", division: 'D3', conference: "North Coast Athletic Conference", state: 'OH', site: "www.woosterathletics.com" },
  { id: "the-state-university-of-new-york-at-fredonia", name: "The State University of New York at Fredonia", division: 'D3', conference: "State University of New York Athletic Conference", state: 'NY', site: "www.fredoniabluedevils.com" },
  { id: "transylvania-university", name: "Transylvania University", division: 'D3', conference: "Heartland Collegiate Athletic Conference", state: 'KY', site: "www.transysports.com" },
  { id: "trinity-college-connecticut", name: "Trinity College (Connecticut)", division: 'D3', conference: "New England Small College Athletic Conference", state: 'CT', site: "www.bantamsports.com" },
  { id: "trinity-university-texas", name: "Trinity University (Texas)", division: 'D3', conference: "Southern Athletic Association", state: 'TX', site: "www.trinitytigers.com" },
  { id: "tufts-university", name: "Tufts University", division: 'D3', conference: "New England Small College Athletic Conference", state: 'MA', site: "www.gotuftsjumbos.com/landing/index" },
  { id: "u-s-coast-guard-academy", name: "U.S. Coast Guard Academy", division: 'D3', conference: "New England Women's and Men's Athletic Conference", state: 'CT', site: "coastguardathletics.com/index.aspx" },
  { id: "u-s-merchant-marine-academy", name: "U.S. Merchant Marine Academy", division: 'D3', conference: "Skyline Conference", state: 'NY', site: "usmmasports.com" },
  { id: "union-college-new-york", name: "Union College (New York)", division: 'D3', conference: "Liberty League", state: 'NY', site: "www.unionathletics.com" },
  { id: "university-of-california-santa-cruz", name: "University of California, Santa Cruz", division: 'D3', conference: "Independent", state: 'CA', site: "www.goslugs.com" },
  { id: "university-of-chicago", name: "University of Chicago", division: 'D3', conference: "University Athletic Association", state: 'IL', site: "athletics.uchicago.edu/landing/index" },
  { id: "university-of-la-verne", name: "University of La Verne", division: 'D3', conference: "Southern California Intercollegiate Athletic Conf.", state: 'CA', site: "www.leopardathletics.com" },
  { id: "university-of-lynchburg", name: "University of Lynchburg", division: 'D3', conference: "Old Dominion Athletic Conf.", state: 'VA', site: "www.lynchburgsports.com/landing/index" },
  { id: "university-of-mary-washington", name: "University of Mary Washington", division: 'D3', conference: "New Jersey Athletic Conference", state: 'VA', site: "www.umweagles.com" },
  { id: "university-of-massachusetts-dartmouth", name: "University of Massachusetts, Dartmouth", division: 'D3', conference: "Little East Conference", state: 'MA', site: "www.corsairathletics.com" },
  { id: "university-of-minnesota-morris", name: "University of Minnesota, Morris", division: 'D3', conference: "Independent", state: 'MN', site: "www.morriscougars.com" },
  { id: "university-of-mount-union", name: "University of Mount Union", division: 'D3', conference: "Ohio Athletic Conference", state: 'OH', site: "athletics.mountunion.edu" },
  { id: "university-of-pittsburgh-bradford", name: "University of Pittsburgh, Bradford", division: 'D3', conference: "State University of New York Athletic Conference", state: 'PA', site: "athletics.pittbradford.org/landing/index" },
  { id: "university-of-puget-sound", name: "University of Puget Sound", division: 'D3', conference: "Northwest Conference", state: 'WA', site: "www.loggerathletics.com" },
  { id: "university-of-redlands", name: "University of Redlands", division: 'D3', conference: "Southern California Intercollegiate Athletic Conf.", state: 'CA', site: "www.goredlands.com" },
  { id: "university-of-rochester", name: "University of Rochester", division: 'D3', conference: "University Athletic Association", state: 'NY', site: "www.rochester.edu/athletics" },
  { id: "university-of-saint-joseph-connecticut", name: "University of Saint Joseph (Connecticut)", division: 'D3', conference: "Great Northeast Athletic Conference", state: 'CT', site: "www.usjbluejays.com" },
  { id: "university-of-scranton", name: "University of Scranton", division: 'D3', conference: "Landmark Conference", state: 'PA', site: "athletics.scranton.edu" },
  { id: "university-of-st-thomas-texas", name: "University of St. Thomas (Texas)", division: 'D3', conference: "Southern Collegiate Athletic Conference", state: 'TX', site: "www.ustcelts.com" },
  { id: "university-of-wisconsin-eau-claire", name: "University of Wisconsin-Eau Claire", division: 'D3', conference: "Wisconsin Intercollegiate Athletic Conference", state: 'WI', site: "www.blugolds.com" },
  { id: "university-of-wisconsin-la-crosse", name: "University of Wisconsin-La Crosse", division: 'D3', conference: "Wisconsin Intercollegiate Athletic Conference", state: 'WI', site: "www.uwlathletics.com" },
  { id: "university-of-wisconsin-oshkosh", name: "University of Wisconsin-Oshkosh", division: 'D3', conference: "Wisconsin Intercollegiate Athletic Conference", state: 'WI', site: "uwoshkoshtitans.com" },
  { id: "university-of-wisconsin-stevens-point", name: "University of Wisconsin-Stevens Point", division: 'D3', conference: "Wisconsin Intercollegiate Athletic Conference", state: 'WI', site: "athletics.uwsp.edu" },
  { id: "university-of-wisconsin-whitewater", name: "University of Wisconsin-Whitewater", division: 'D3', conference: "Wisconsin Intercollegiate Athletic Conference", state: 'WI', site: "www.uwwsports.com" },
  { id: "university-of-the-ozarks-arkansas", name: "University of the Ozarks (Arkansas)", division: 'D3', conference: "Southern Collegiate Athletic Conference", state: 'AR', site: "www.uofoathletics.com/landing/index" },
  { id: "university-of-the-south", name: "University of the South", division: 'D3', conference: "Southern Athletic Association", state: 'TN', site: "sewaneetigers.com" },
  { id: "ursinus-college", name: "Ursinus College", division: 'D3', conference: "Centennial Conference", state: 'PA', site: "www.ursinusathletics.com" },
  { id: "vassar-college", name: "Vassar College", division: 'D3', conference: "Liberty League", state: 'NY', site: "www.vassarathletics.com" },
  { id: "wabash-college", name: "Wabash College", division: 'D3', conference: "North Coast Athletic Conference", state: 'IN', site: "sports.wabash.edu" },
  { id: "warren-wilson-college", name: "Warren Wilson College", division: 'D3', conference: "Independent", state: 'NC', site: "warrenwilsonowls.com/landing/index" },
  { id: "washington-college-maryland", name: "Washington College (Maryland)", division: 'D3', conference: "Centennial Conference", state: 'MD', site: "www.washingtoncollegesports.com" },
  { id: "washington-university-in-st-louis", name: "Washington University in St. Louis", division: 'D3', conference: "University Athletic Association", state: 'MO', site: "washubears.com" },
  { id: "washington-and-jefferson-college", name: "Washington and Jefferson College", division: 'D3', conference: "Presidents' Athletic Conference", state: 'PA', site: "www.gopresidents.com" },
  { id: "washington-and-lee-university", name: "Washington and Lee University", division: 'D3', conference: "Old Dominion Athletic Conf.", state: 'VA', site: "generalssports.com" },
  { id: "wesleyan-university-connecticut", name: "Wesleyan University (Connecticut)", division: 'D3', conference: "New England Small College Athletic Conference", state: 'CT', site: "www.wesleyan.edu/athletics" },
  { id: "westminster-college-pennsylvania", name: "Westminster College (Pennsylvania)", division: 'D3', conference: "Presidents' Athletic Conference", state: 'PA', site: "www.westminster.edu/athletics" },
  { id: "wheaton-college-illinois", name: "Wheaton College (Illinois)", division: 'D3', conference: "College Conference of Illinois & Wisconsin", state: 'IL', site: "athletics.wheaton.edu" },
  { id: "wheaton-college-massachusetts", name: "Wheaton College (Massachusetts)", division: 'D3', conference: "New England Women's and Men's Athletic Conference", state: 'MA', site: "wheatoncollegelyons.com" },
  { id: "whitman-college", name: "Whitman College", division: 'D3', conference: "Northwest Conference", state: 'WA', site: "www.whitman.edu/athletics" },
  { id: "whittier-college", name: "Whittier College", division: 'D3', conference: "Southern California Intercollegiate Athletic Conf.", state: 'CA', site: "www.wcpoets.com" },
  { id: "whitworth-university", name: "Whitworth University", division: 'D3', conference: "Northwest Conference", state: 'WA', site: "www.whitworthpirates.com" },
  { id: "widener-university", name: "Widener University", division: 'D3', conference: "Middle Atlantic Conferences", state: 'PA', site: "www.widenerpride.com" },
  { id: "wilkes-university", name: "Wilkes University", division: 'D3', conference: "Landmark Conference", state: 'PA', site: "www.gowilkesu.com" },
  { id: "willamette-university", name: "Willamette University", division: 'D3', conference: "Northwest Conference", state: 'OR', site: "willamette.prestosports.com/landing/index" },
  { id: "william-paterson-university-of-new-jersey", name: "William Paterson University of New Jersey", division: 'D3', conference: "New Jersey Athletic Conference", state: 'NJ', site: "www.wpupioneers.com" },
  { id: "william-peace-university", name: "William Peace University", division: 'D3', conference: "Independent", state: 'NC', site: "www.gopeacepacers.com" },
  { id: "williams-college", name: "Williams College", division: 'D3', conference: "New England Small College Athletic Conference", state: 'MA', site: "ephsports.williams.edu" },
  { id: "wilmington-college-ohio", name: "Wilmington College (Ohio)", division: 'D3', conference: "Ohio Athletic Conference", state: 'OH', site: "www.wilmington.edu/athletics" },
  { id: "wittenberg-university", name: "Wittenberg University", division: 'D3', conference: "North Coast Athletic Conference", state: 'OH', site: "www.wittenbergtigers.com" },
  { id: "worcester-polytechnic-institute", name: "Worcester Polytechnic Institute", division: 'D3', conference: "New England Women's and Men's Athletic Conference", state: 'MA', site: "athletics.wpi.edu" },
  { id: "york-college-new-york", name: "York College (New York)", division: 'D3', conference: "City University of New York Athletic Conference", state: 'NY', site: "www.yorkathletics.com" },
  { id: "york-college-pennsylvania", name: "York College (Pennsylvania)", division: 'D3', conference: "Middle Atlantic Conferences", state: 'PA', site: "www.ycpspartans.com" }
];

function byDivision(division) {
  return ROSTER.filter(function (s) { return s.division === division; });
}

// Search as a person actually types, ie, part of a name, a state code, or a
// conference. Nothing clever, just forgiving.
function search(query, limit) {
  const q = String(query || '').trim().toLowerCase();
  if (q.length < 2) return [];
  const hits = ROSTER.filter(function (s) {
    return s.name.toLowerCase().indexOf(q) !== -1 ||
      s.conference.toLowerCase().indexOf(q) !== -1 ||
      acronymMatches(s.conference, q) ||
      s.state.toLowerCase() === q ||
      s.division.toLowerCase() === q;
  });
  // A name match is what was meant nine times in ten, so it leads.
  hits.sort(function (a, b) {
    const an = a.name.toLowerCase().indexOf(q) === -1 ? 1 : 0;
    const bn = b.name.toLowerCase().indexOf(q) === -1 ? 1 : 0;
    if (an !== bn) return an - bn;
    return a.name.localeCompare(b.name);
  });
  return hits.slice(0, limit || 25);
}

// The directory spells conferences out in full, ie, "Metro Atlantic Athletic
// Conference". Nobody types that. They type MAAC.
//
// Both forms count, with and without the trailing letter from the word
// "Conference", because usage is genuinely split: it is MAAC with the C and
// PSAC with it, but people type "Patriot" rather than PL. Trimming the C
// unconditionally turned maac into maa and matched nothing, which is the bug
// this comment exists to stop someone reintroducing.
function acronym(name) {
  return String(name || '')
    .split(/\s+/)
    .filter(function (w) { return /^[A-Z]/.test(w) && !/^(of|the|and|for)$/i.test(w); })
    .map(function (w) { return w[0]; })
    .join('')
    .toLowerCase();
}

// The directory does not always use the name people know. It lists the MAAC
// schools under "Metro Conference". This maps what someone types to what the
// source actually says. Only add an entry here when the difference has been
// seen in the data, ie, never guess a conference into existence.
const ALIASES = {
  maac: 'metro conference'
};

function acronymMatches(name, q) {
  if (ALIASES[q] && String(name || '').toLowerCase() === ALIASES[q]) return true;
  const full = acronym(name);
  if (!full) return false;
  return full === q || full.replace(/c$/, '') === q;
}

function counts() {
  const out = {};
  ROSTER.forEach(function (s) { out[s.division] = (out[s.division] || 0) + 1; });
  out.total = ROSTER.length;
  return out;
}

const api = {
  SOURCE: SOURCE,
  RECORDED: RECORDED,
  ROSTER: ROSTER,
  byDivision: byDivision,
  search: search,
  acronym: acronym,
  acronymMatches: acronymMatches,
  ALIASES: ALIASES,
  counts: counts
};

if (typeof module !== 'undefined' && module.exports) module.exports = api;
if (typeof window !== 'undefined') window.Roster = api;

})();
